# Generated by Django 4.2.5 on 2023-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100)),
                ('solicitacao', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('r', models.CharField(max_length=100)),
                ('nc', models.CharField(max_length=100)),
                ('lm', models.CharField(max_length=100)),
            ],
        ),
    ]
